### ISSUE TITLE
JukeBox Feature

### ISSUE THREAD

**Issue by Ismael-GT** [SkytAsul/JukeBox#1]
Hello!, I have a network with a minigame focing to my player playing and stopping sounds constantly, The messages received by the player of the sounds being played are very ugly. I suggest a feature with the capacity to hide it, if it is posibble, please! :D

```
#The command "/adminmusic stop" and "asadmin play", The player will not receive any messages.
silentmode: false
```

**Comment by SkytAsul** [comment]
This is already possible.
https://github.com/SkytAsul/JukeBox/blob/1982ab09612b1df2286d2c70ca7a412e2390a1c0/src/main/resources/config.yml#L11
