### ISSUE TITLE
Bug? Disc IDs Start At 0

### ISSUE THREAD

**Issue by Korrivyn** [SkytAsul/JukeBox#10]
For displaying purposes to players I'd like to see the IDs start at 1 instead of 0. Minor detail, but one I caught as I was mucking about.

**Comment by SkytAsul** [comment]
IDs are not meant to be seen by players. Arrays all start at 0, that's how computers work, unfortunately :/

**Comment by Korrivyn** [comment]
Then this is still an issue and they should be hidden as they currently show to players, firstly. Secondly just because array indexes start at zero doesn't mean you can't humanize them by having a 'dummy' 0, or displaying the ID as index + 1, then when using it in commands reduce use the provided ID as index - 1.

**Comment by SkytAsul** [comment]
Unfortunately, this would be a breaking change as several servers are already using the 0-starting system.
I will make the IDs hidden for players.
