### ISSUE TITLE
Feature Request: More Permission Nodes

### ISSUE THREAD

**Issue by notenoughbees** [SkytAsul/JukeBox#24]
I'd appreciate more ability for customisation so that we can restrict certain parts of the plugin to certain ranks, for example, let the lowest rank able to play a random song, while higher ranks can use the radio to play multiple songs nonstop. My ideas for permissions are:
* music.random: can use the Random Music button
* music.radio: can use the Radio playlist
* music.favourites: can add music to the Favourites playlist & play that playlist
* music.particles: can use particles mode
* music.play-on-join: can let music play when joining
* music.shuffle: can use shuffle mode
* music.loop: can use loop mode

At the moment, Jukebox has only 3 permission nodes, so I think it'd be great to have more.

**Comment by SkytAsul** [comment]
Done in JukeBox 1.20!
