### ISSUE TITLE
Many messages not configurable

### ISSUE THREAD

**Issue by notenoughbees** [SkytAsul/JukeBox#25]
On my Paper 1.16.4 server, running Jukebox 1.19.5, at least a third of the messages in en.yml aren't actually configurable.

I went to see just how many aren't configurable by setting every single message to "x", and the messages that didn't change were these:
TOGGLE_PLAYING
RANDOM_MUSIC
STOP
MUSIC_STOPPED
RELOAD_LAUNCH
PLAYLIST_ITEM
OPTIONS_ITEM
MENU_ITEM
CLEAR_PLAYLIST
NEXT_ITEM
CHANGE_PLAYLIST
CHANGE_PLAYLIST_LORE
PLAYLIST
FAVORITES
RADIO

Most of them are GUI messages, and a lot of them are important messages like the titles of buttons, so it'd be massively great to have this fixed :)

![messages](https://user-images.githubusercontent.com/62003733/100539998-57410580-329f-11eb-9785-b8f629e8fb80.png)

**Comment by SkytAsul** [comment]
All of those actually are configurable. Have you tried restarting the server instead of just reloading the plugin? I'm caching the items with their names at startup to not overload the server.

**Comment by notenoughbees** [comment]
Yes I was just reloading instead of restarting, just restarted now and it all works! I'll close this, thanks :)
