### ISSUE TITLE
Custom Pitches and Instruments

### ISSUE THREAD

**Issue by MericGit** [SkytAsul/JukeBox#3]
I'm not quite sure if it's something on my end, but in NBS when I use custom pitches (exceeding the vanilla mc octave range) or custom instruments, the plugin doesn't seem to play it properly.

(I have the correct resource pack). If I export the nbs file to a datapack it plays fine, but through the plugin it doesn't play any of the custom pitches or instruments.

Could you look into this? (And If I'm missing something and am being dumb, so sorry)

Thanks!

**Comment by SkytAsul** [comment]
This issue belongs to NoteBlockAPI. Please report it [here](https://github.com/koca2000/NoteBlockAPI/issues)!
