### ISSUE TITLE
Check whether Player-Inventory is not occupied by other GUI Systems

### ISSUE THREAD

**Issue by RedstoneFuture** [SkytAsul/JukeBox#55]
Does it make sense to have JukeBox check that the GUI is not being used by other plugins? The [DeluxeMenus](https://github.com/HelpChat/DeluxeMenus) plugin, for example, simply does not open the inventory (without comment) in this case. Since JukeBox also allows the menus to be opened as a command from anywhere, I could imagine that it would make more sense for JukeBox to check itself before opening.

In my case, the inventory on the game server is permanently occupied by a game system in certain regions. When I execute `/jukebox`, I get an error in this region: https://bytebin.lucko.me/RuXJW7UzG8

---

Tested with `JukeBox v1.20.9` on `PaperMC 1.20.4, build 496`

**Comment by SkytAsul** [comment]
Then prevent players from doing `/jukebox` while being in your custom inventory system. Not opening the inventory without comment like DeluxeMenus is doing is a bad practice. Swallowing errors like that is the best way to be confused when something goes wrong.
Besides, I am no longer actively working on JukeBox. You can fork the source code and make it to work with your setup, that's one of the great benefits of open source software :)

**Comment by RedstoneFuture** [comment]
> Not opening the inventory without comment like DeluxeMenus is doing is a bad practice.

Yes, I don't think that's so good either.

Thank you for the quick reply. Now I have your view and I'll see what I do.
