### ISSUE TITLE
Can I use the new Bukkit API?

### ISSUE THREAD

**Issue by yuqian114514** [SkytAsul/JukeBox#58]
Author Your plugin uses the old version of the Bukkit API and uses a class called InventoryView, but now the new version of the Bukkit API is already an interface and is not compatible with the new version of the Bukkit API, can you upgrade the Bukkit API?

**Comment by SkytAsul** [comment]
This is already done with the latest Jukebox version (1.20.12).

**Comment by RisingRealmMinecraftserver** [comment]
Then why isn't the configuration file generated
