### ISSUE TITLE
Feature Request; More Placeholders

### ISSUE THREAD

**Issue by Korrivyn** [SkytAsul/JukeBox#9]
I'd appreciate being able to have a placeholder for song name & author separately so it can be animated to go between them to save space in our tab list. %jukebox_active_name% and %jukebox_active_author%, for example. Might also be worth doing %jukebox_active_desc%, though that's not as pressing for me, personally.

Another option would be to provide a placeholder that scrolls through the title at a set width (set in the config or on placeholder call) so it's legible at whatever width one would like.

**Comment by SkytAsul** [comment]
Done in https://github.com/SkytAsul/JukeBox/commit/78bafdf11728cd9f647309bc9c0d5b39dba34c6b
